### ISSUE TITLE
standalone文件的evaluate有缺失

### ISSUE THREAD

**Issue by Zzy9797** [SMILELab-FL/FedLab#331]
您好，我在跑quickstart的时候，发现standalone的evaluate的函数里面没有内容，现在跑完的是没有任何测试结果的，可以麻烦添加一下嘛

**Comment by Zengdun-cs** [comment]
你好，可以先参考example下的demo,或者是tutotials下的stand-alone部分---- 回复的原邮件 ***@***.***>发送日期2023年09月10日 19:03 ***@***.***> ***@***.***>主题[SMILELab-FL/FedLab] standalone文件的evaluate有缺失 (Issue #331)
您好，我在跑quickstart的时候，发现standalone的evaluate的函数里面没有内容，现在跑完的是没有任何测试结果的，可以麻烦添加一下嘛

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/SMILELab-FL/FedLab/issues/331",
"url": "https://github.com/SMILELab-FL/FedLab/issues/331",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AgentDS** [comment]
可以参考[这个](https://github.com/SMILELab-FL/FedNoisy/blob/c62d0a722624aa6132b2c5eaaf757be84fa2d749/fednoisy/algorithms/fedavg/standalone.py#L100C7-L100C7)

**Comment by AgentDS** [comment]
你好，最新的master 分支下已更新evaluate部分。
